name: Build and deploy

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:

  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build and push
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          BASE_URL: https://ops.adrienparra.eu
          IMAGE_NAME: rg.fr-par.scw.cloud/funcscwportfolio7b05b454/portfolio
          IMAGE_TAG: latest
        run: |
          echo "${REGISTRY_TOKEN}" | docker login rg.fr-par.scw.cloud/funcscwportfolio7b05b454 -u nologin --password-stdin
          docker image build -f packaging/Dockerfile --build-arg BASE_URL=${BASE_URL} -t ${IMAGE_NAME}:${IMAGE_TAG} .
          docker image push ${IMAGE_NAME}:${IMAGE_TAG}

  deploySCW:
    runs-on: ubuntu-latest
    container:
      image: scaleway/cli:2.54
      options: --entrypoint ""
    needs: [buildImage]
    steps:
      - name: Deploy container to Serverless
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_CONTAINER_ID: ${{ secrets.SCW_CONTAINER_ID }}
        run: |
          scw container container deploy ${SCW_CONTAINER_ID} region=fr-par --wait

